const SHOP_DATA = [
  {
    id: 1,
    category: 'hats',
    name: 'Brown Brim',
    imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
    price: 25,
  },
  {
    id: 2,
    category: 'hats',
    name: 'Blue Beanie',
    imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
    price: 18,
  },
  {
    id: 3,
    category: 'hats',
    name: 'Brown Cowboy',
    imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
    price: 35,
  },
  {
    id: 4,
    category: 'hats',
    name: 'Grey Brim',
    imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
    price: 25,
  },
  {
    id: 5,
    category: 'hats',
    name: 'Green Beanie',
    imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
    price: 18,
  },
  {
    id: 6,
    category: 'hats',
    name: 'Palm Tree Cap',
    imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
    price: 14,
  },
  {
    id: 7,
    category: 'hats',
    name: 'Red Beanie',
    imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
    price: 18,
  },
  {
    id: 8,
    category: 'hats',
    name: 'Wolf Cap',
    imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
    price: 14,
  },
  {
    id: 9,
    category: 'hats',
    name: 'Blue Snapback',
    imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
    price: 16,
  },
  {
    id: 10,
    category: 'sneakers',
    name: 'Adidas NMD',
    imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
    price: 220,
  },
  {
    id: 11,
    category: 'sneakers',
    name: 'Adidas Yeezy',
    imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
    price: 280,
  },
  {
    id: 12,
    category: 'sneakers',
    name: 'Black Converse',
    imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
    price: 110,
  },
  {
    id: 13,
    category: 'sneakers',
    name: 'Nike White AirForce',
    imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
    price: 160,
  },
  {
    id: 14,
    category: 'sneakers',
    name: 'Nike Red High Tops',
    imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
    price: 160,
  },
  {
    id: 15,
    category: 'sneakers',
    name: 'Nike Brown High Tops',
    imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
    price: 160,
  },
  {
    id: 16,
    category: 'sneakers',
    name: 'Air Jordan Limited',
    imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
    price: 190,
  },
  {
    id: 17,
    category: 'sneakers',
    name: 'Timberlands',
    imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
    price: 200,
  },
  {
    id: 18,
    category: 'jackets',
    name: 'Black Jean Shearling',
    imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
    price: 125,
  },
  {
    id: 19,
    category: 'jackets',
    name: 'Blue Jean Jacket',
    imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
    price: 90,
  },
  {
    id: 20,
    category: 'jackets',
    name: 'Grey Jean Jacket',
    imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
    price: 90,
  },
  {
    id: 21,
    category: 'jackets',
    name: 'Brown Shearling',
    imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
    price: 165,
  },
  {
    id: 22,
    category: 'jackets',
    name: 'Tan Trench',
    imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
    price: 185,
  },
  {
    id: 23,
    category: 'women',
    name: 'Blue Tanktop',
    imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
    price: 25,
  },
  {
    id: 24,
    category: 'women',
    name: 'Floral Blouse',
    imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
    price: 20,
  },
  {
    id: 25,
    category: 'women',
    name: 'Floral Dress',
    imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
    price: 80,
  },
  {
    id: 26,
    category: 'women',
    name: 'Red Dots Dress',
    imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
    price: 80,
  },
  {
    id: 27,
    category: 'women',
    name: 'Striped Sweater',
    imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
    price: 45,
  },
  {
    id: 28,
    category: 'women',
    name: 'Yellow Track Suit',
    imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
    price: 135,
  },
  {
    id: 29,
    category: 'women',
    name: 'White Blouse',
    imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
    price: 20,
  },
  {
    id: 30,
    category: 'men',
    name: 'Camo Down Vest',
    imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
    price: 325,
  },
  {
    id: 31,
    category: 'men',
    name: 'Floral T-shirt',
    imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
    price: 20,
  },
  {
    id: 32,
    category: 'men',
    name: 'Black & White Longsleeve',
    imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
    price: 25,
  },
  {
    id: 33,
    category: 'men',
    name: 'Pink T-shirt',
    imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
    price: 25,
  },
  {
    id: 34,
    category: 'men',
    name: 'Jean Long Sleeve',
    imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
    price: 40,
  },
  {
    id: 35,
    category: 'men',
    name: 'Burgundy T-shirt',
    imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
    price: 25,
  },
  {
    id: 36,
    category: 'men',
    name: 'Ghoghari Summer Style',
    imageUrl: 'https://m.media-amazon.com/images/I/51YYsimvWGL.jpg',
    price: 25,
  },
  {
    id: 37,
    category: 'men',
    name: 'Navy Regular',
    imageUrl:
      'https://assets.myntassets.com/dpr_1.5,q_60,w_400,c_limit,fl_progressive/assets/images/2284693/2019/7/11/93e90c1d-c931-4871-9cf2-6df95911b6731562829612019-Roadster-Men-Navy-Regular-Fit-Solid-Casual-Shirt-46915628296-1.jpg',
    price: 25,
  },
  {
    id: 38,
    category: 'jackets',
    name: 'Casual Zipper',
    imageUrl:
      'https://img.joomcdn.net/d61ad69a5137432ff9ba0a27b1bf06b354642d12_original.jpeg',
    price: 34,
  },
  {
    id: 39,
    category: 'jackets',
    name: 'Leather Coats',
    imageUrl:
      'https://i.pinimg.com/736x/73/f8/57/73f857050959990f6af9f2a9175b765e--short-jackets-leather-coats.jpg',
    price: 65,
  },
  {
    id: 40,
    category: 'jackets',
    name: 'Cropped Jacket',
    imageUrl:
      'https://image.uniqlo.com/UQ/ST3/id/imagesgoods/448126/item/idgoods_64_448126.jpg?width=1008&impolicy=quality_75',
    price: 65,
  },
  {
    id: 41,
    category: 'women',
    name: 'Casual Office Wear',
    imageUrl:
      'https://i.insider.com/609c4b446a3ce80019e04208?width=1000&format=jpeg&auto=webp',
    price: 45,
  },
  {
    id: 42,
    category: 'hats',
    name: 'Navy Blue Beanie',
    imageUrl:
      'https://i.insider.com/56a8f2a9c08a806f008bcd9c?width=889&format=jpeg',
    price: 25,
  },
  {
    id: 43,
    category: 'hats',
    name: 'Gabardine Goggle Cap',
    imageUrl:
      'https://www.cpcompany.com/on/demandware.static/-/Sites-cpc-master-catalog/default/dw63f96edb/images/hi-res-1/11CMAC240A005279A999.3.H1.jpg',
    price: 20,
  },
  {
    id: 44,
    category: 'hats',
    name: 'Bamboo Chemo Turban',
    imageUrl:
      'https://www.oncovia.com/25001/bamboo-turban-mathilde-light-pink-japan.jpg',
    price: 20,
  },
  {
    id: 45,
    category: 'jackets',
    name: 'Hashirama ',
    imageUrl:
      'https://animehoodie.com/wp-content/uploads/2021/08/unisex-captain-america-3d-print-fashion-hoodies.jpg',
    price: 74,
  },
  {
    id: 46,
    category: 'jackets',
    name: 'Kakashi',
    imageUrl:
      'https://www.u-buy.com.ng/productimg/?image=aHR0cHM6Ly9pbWFnZXMtbmEuc3NsLWltYWdlcy1hbWF6b24uY29tL2ltYWdlcy9JLzYxNGw4UnF1TktMLl9TUzQwMF8uanBn.jpg',
    price: 67,
  },
  {
    id: 47,
    category: 'jackets',
    name: 'Naruto Hoodie',
    imageUrl:
      'https://i.pinimg.com/474x/86/c0/7b/86c07bc46fa76692dda40893dbfa112a.jpg',
    price: 60,
  },
  {
    id: 48,
    category: 'jackets',
    name: 'Sage of Six Path',
    imageUrl:
      'https://cdn.shopify.com/s/files/1/2241/3689/products/gearhuman-3d-naruto-obito-sage-of-six-paths-custom-tshirt-hoodie-apparel-cw08125-3d-apparel-950719_530x@2x.jpg?v=1626779072',
    price: 60,
  },
];

export default SHOP_DATA;
