const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM:'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: ' CLEAR_ITEM_FROM_CART',
  CHECK_OUT_CLEAR_OUT:'CHECK_OUT_CLEAR_OUT'
};

export default CartActionTypes;
